# Tupla de notas com média (sem alterar a tupla)

nota1= float(input("Digite a primeira nota: "))
nota2= float(input("Digite a segunda nota: "))
nota3= float(input("Digite a terceira nota: "))
notas = (nota1, nota2, nota3)
print('----------------------------------------')
print("Notas: ", notas)
print('----------------------------------------')
print("Média: ", sum(notas) / len(notas))